image: docker:19.03.12
variables:
  #DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://10.10.12.67:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:19.03.12-dind
stages:
  - build
  - deploy
build-image:
  stage: build
  script:
    - docker build --build-arg HTTP_PROXY="http://10.10.12.38:3128" --build-arg HTTPS_PROXY="http://10.10.12.38:3128" -t test/vueapp .

deploy-image:
  before_script:
  - export HTTP_PROXY="http://10.10.12.38:3128"
  - export HTTPS_PROXY="http://10.10.12.38:3128"
  - export NO_PROXY=".noproxy.com,.noproxy2.com"
  - env | grep PROXY
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - env | grep PROXY
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  stage: deploy
  image: docker/compose:latest
  script:
    - DOCKER_HOST="ssh://user@10.10.12.99" docker-compose up -d
    #- docker-compose -H "ssh://user@10.10.12.99" up -d
    #- docker stop vueapp-test
    #- docker rm vueapp-test
    #- docker run -d -p 2222:80 --rm --name vueapp-test test/vueapp
