image: docker:19.03.12
variables:
  #DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://10.10.12.67:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:19.03.12-dind

stages:
  - build
  - deploy
build-image:
  stage: build
  script:
    - docker build --build-arg HTTP_PROXY="http://10.10.12.38:3128" --build-arg HTTPS_PROXY="http://10.10.12.38:3128" -t test/vueapp .

deploy-image:
  stage: deploy
  script:
    - docker stop vueapp-test
    - docker rm vueapp-test
    - docker run -d -p 2222:80 --rm --name vueapp-test test/vueapp
