image: docker:19.03.12
variables:
  #DOCKER_TLS_CERTDIR: ''
  #DOCKER_HOST: tcp://0.0.0.0:2375
  #DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:19.03.12-dind
before_script:
  - docker info
stages:
  - deploy
step-deploy-prod:
  stage: deploy
  script:
    - docker build --build-arg HTTP_PROXY="http://10.10.12.38:3128" --build-arg HTTPS_PROXY="http://10.10.12.38:3128" -t test/vueapp .
    - docker run -d -p 80:80 --rm --name todoapp test/vueapp
